# AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
# AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
# AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
# AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

name: PYTHON IN THE CODE OH NO

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: goofy

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stop Service
        continue-on-error: true
        run: sudo systemctl is-active a-terrible-idea && sudo systemctl stop a-terrible-idea

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Create virtual environment
        run: python -m venv venv

      - name: Install dependencies
        run: |
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env file
        run: echo "TOKEN_DISCORD_BOT=${{ secrets.TOKEN_DISCORD_BOT }}" > .env

      - name: Start Service
        run: sudo systemctl start a-terrible-idea
